"""create_recommendations_table

Revision ID: 10f95cc3555f
Revises: a020b6b584a7
Create Date: 2026-08-05 16:30:16.381090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f95cc3555f'
down_revision: Union[str, Sequence[str], None] = 'a020b6b584a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.Enum('TRAFFIC_MANAGEMENT', 'ROUTE_OPTIMIZATION', 'SIGNAL_OPTIMIZATION', 'EMERGENCY_RESPONSE', 'INFRASTRUCTURE_IMPROVEMENT', 'PUBLIC_ADVISORY', 'SAFETY_RECOMMENDATION', name='recommendationcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='recommendationpriority'), nullable=False),
    sa.Column('affected_road', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('expected_impact', sa.String(length=500), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IMPLEMENTED', 'DISMISSED', name='recommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
