"""create traffic and congestion tables

Revision ID: 50b51b46fa8f
Revises: 32662c7f1474
Create Date: 2026-07-09 07:30:14.415815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b51b46fa8f'
down_revision: Union[str, Sequence[str], None] = '32662c7f1474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('congestion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_name', sa.String(length=100), nullable=False),
    sa.Column('current_congestion', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CLEAR', 'MODERATE', 'HEAVY', 'BLOCKED', name='congestionstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_congestion_records_id'), 'congestion_records', ['id'], unique=False)
    op.create_table('traffic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('traffic_density', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='congestionlevel'), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_data_id'), 'traffic_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_data_id'), table_name='traffic_data')
    op.drop_table('traffic_data')
    op.drop_index(op.f('ix_congestion_records_id'), table_name='congestion_records')
    op.drop_table('congestion_records')
    # ### end Alembic commands ###
