"""create_reports_table

Revision ID: 64cd2e4abe60
Revises: 50b51b46fa8f
Create Date: 2026-07-24 04:20:01.008295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cd2e4abe60'
down_revision: Union[str, Sequence[str], None] = '50b51b46fa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('filters_applied', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_reports_id'), 'traffic_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_reports_id'), table_name='traffic_reports')
    op.drop_table('traffic_reports')
    # ### end Alembic commands ###
