from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import StreamingResponse
from typing import List, Optional
from sqlalchemy.orm import Session
from database.database import get_db
from core.dependencies import get_current_active_user, get_operator_user, get_admin_user
from models.user import User
from reports.service import reports_service
from reports.schemas import AIReportCreate, AIReportResponse, AIReportSummary

router = APIRouter(prefix="/api/v1/reports", tags=["Traffic AI Reports"])

@router.get("", response_model=List[AIReportResponse])
def get_reports(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Get a list of all reports generated by the authenticated user.
    """
    try:
        return reports_service.get_reports_list(db, user_id=current_user.id)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch reports: {str(e)}"
        )

@router.get("/summary", response_model=AIReportSummary)
def get_reports_summary(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Get report summary counts for dashboard dashboard cards.
    """
    try:
        return reports_service.get_reports_kpi_summary(db, user_id=current_user.id)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to load reports summary: {str(e)}"
        )

@router.post("/generate", response_model=AIReportResponse, status_code=status.HTTP_201_CREATED)
def generate_report(
    payload: AIReportCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_admin_user)
):
    """
    Generate and save a new AI traffic analysis report.
    """
    try:
        report_dict = payload.model_dump()
        return reports_service.generate_and_save_report(db, report_dict, user_id=current_user.id)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate and save report: {str(e)}"
        )

@router.get("/{id}", response_model=AIReportResponse)
def get_report_detail(
    id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Get details of a single generated report by ID.
    """
    rep = reports_service.get_report_by_id(db, id, user_id=current_user.id)
    if not rep:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found."
        )
    return rep

# Export endpoints
@router.get("/export/pdf")
def export_pdf(
    report_id: Optional[int] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    region: Optional[str] = None,
    road_type: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Export report as PDF. Streams a compiled binary file.
    """
    try:
        if report_id:
            rep = reports_service.get_report_by_id(db, report_id, user_id=current_user.id)
            if not rep:
                raise HTTPException(status_code=404, detail="Report not found")
            summary_data = rep.summary_data
        else:
            filters = {"start_date": start_date, "end_date": end_date, "region": region, "road_type": road_type}
            summary_data = reports_service.compile_report_data(db, filters)

        pdf_buffer = reports_service.compile_pdf_buffer(summary_data)
        
        filename = f"TrafficVision_Report_{report_id or 'live'}.pdf"
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to compile PDF: {str(e)}"
        )

@router.get("/export/csv")
def export_csv(
    report_id: Optional[int] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    region: Optional[str] = None,
    road_type: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Export report as CSV. Streams a text CSV file.
    """
    try:
        if report_id:
            rep = reports_service.get_report_by_id(db, report_id, user_id=current_user.id)
            if not rep:
                raise HTTPException(status_code=404, detail="Report not found")
            summary_data = rep.summary_data
        else:
            filters = {"start_date": start_date, "end_date": end_date, "region": region, "road_type": road_type}
            summary_data = reports_service.compile_report_data(db, filters)

        csv_io = reports_service.compile_csv_buffer(summary_data)
        
        filename = f"TrafficVision_Report_{report_id or 'live'}.csv"
        return StreamingResponse(
            iter([csv_io.getvalue()]),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to compile CSV: {str(e)}"
        )

@router.get("/export/excel")
def export_excel(
    report_id: Optional[int] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    region: Optional[str] = None,
    road_type: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_operator_user)
):
    """
    Export report as Excel. Streams a compiled binary workbook (.xlsx).
    """
    try:
        if report_id:
            rep = reports_service.get_report_by_id(db, report_id, user_id=current_user.id)
            if not rep:
                raise HTTPException(status_code=404, detail="Report not found")
            summary_data = rep.summary_data
        else:
            filters = {"start_date": start_date, "end_date": end_date, "region": region, "road_type": road_type}
            summary_data = reports_service.compile_report_data(db, filters)

        xlsx_buffer = reports_service.compile_excel_buffer(summary_data)
        
        filename = f"TrafficVision_Report_{report_id or 'live'}.xlsx"
        return StreamingResponse(
            xlsx_buffer,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to compile Excel workbook: {str(e)}"
        )
